codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    range: 75..100
    round: down
    precision: 2
    status:
        project:
            default:
                enabled: yes
                target: 75%
                threshold: 10%
                if_ci_failed: error
        patch: off
